
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>BiomeExtractorsMod</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Calamity\Content\MapIcons\ThermoresistantExtractorIcon.png" />
    <None Remove="Calamity\Content\Tiles\AbyssalExtractorTile_Glow.png" />
    <None Remove="Calamity\Content\Tiles\AuricExtractorTile_Glow.png" />
    <None Remove="Calamity\Content\Tiles\SpectralExtractorTile_Glow.png" />
    <None Remove="Calamity\Content\Tiles\SulphuricExtractorTile_Glow.png" />
    <None Remove="Calamity\Content\Tiles\ThermoresistantExtractorTile_Glow.png" />
    <None Remove="Content\Items\BiomeExtractorItemAdamantite.png" />
    <None Remove="Content\Items\BiomeExtractorItemCorruption.png" />
    <None Remove="Content\Items\BiomeExtractorItemCrimson.png" />
    <None Remove="Content\Items\BiomeExtractorItemCyber.png" />
    <None Remove="Content\Items\BiomeExtractorItemEthereal.png" />
    <None Remove="Content\Items\BiomeExtractorItemInfernal.png" />
    <None Remove="Content\Items\BiomeExtractorItemLead.png" />
    <None Remove="Content\Items\BiomeExtractorItemLunar.png" />
    <None Remove="Content\Items\BiomeExtractorItemTitanium.png" />
    <None Remove="Content\Items\BiomeScanner.png" />
    <None Remove="Content\Items\UpgradeKitCrimson.png" />
    <None Remove="Content\Tiles\BiomeExtractorTileCyber.png" />
    <None Remove="Content\Tiles\BiomeExtractorTileDemonic.png" />
    <None Remove="Content\Tiles\BiomeExtractorTileEthereal.png" />
    <None Remove="Content\Tiles\BiomeExtractorTileInfernal.png" />
    <None Remove="Content\Tiles\BiomeExtractorTileLunar.png" />
    <None Remove="Content\Tiles\BiomeExtractorTileSteampunk.png" />
    <None Remove="description_workshop.txt" />
    <None Remove="Localization\it-IT_Mods.BiomeExtractorsMod.hjson" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CalamityMod">
      <HintPath>..\ModAssemblies\CalamityMod_v2.1.2.dll</HintPath>
    </Reference>
    <Reference Include="MagicStorage">
      <HintPath>..\ModAssemblies\MagicStorage_v0.7.0.11.dll</HintPath>
    </Reference>
    <Reference Include="MagicStorage">
      <HintPath>..\ModAssemblies\MagicStorage_v0.7.0.4.dll</HintPath>
    </Reference>
    <Reference Include="SubworldLibrary">
      <HintPath>..\ModAssemblies\SubworldLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Content\MapIcons\" />
  </ItemGroup>
</Project>